In [30]:
import numpy as np
import pandas as pd
from google.colab import drive

In [31]:
drive = drive.mount('/content/drive/')
data_path = '/content/drive/My Drive/Colab_Data/AirBnb/Italy/Sicily/'

#save the DF so we don't have to keep doing geo lookups
file_path = data_path + f'derived/abnb_geo_df_500.csv'
abnb_df = pd.read_csv(file_path)

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).

In [32]:
abnb_df.drop(columns=['Unnamed: 0', 'Unnamed: 0.1'], inplace=True)
abnb_df.head()

,id,listing_url,latitude,longitude,geo_state,geo_country_code,geo_county,geo_postcode,geo_road,geo_town,geo_village,geo_city,geo_suburb,geo_hamlet,geo_neighbourhood,geo_quarter,geo_common_name
0,207654,https://www.airbnb.com/rooms/207654,37.61484,15.01867,Sicilia,it,Catania,95030.0,Viale Aldo Moro,NaN,Nicolosi,NaN,NaN,NaN,NaN,NaN,Nicolosi
1,125569,https://www.airbnb.com/rooms/125569,37.61566,15.01782,Sicilia,it,Catania,95030.0,Viale Aldo Moro,NaN,Nicolosi,NaN,NaN,NaN,NaN,NaN,Nicolosi
2,702537,https://www.airbnb.com/rooms/702537,37.57494,12.74790,Sicilia,it,Trapani,91021.0,Viale Nicolò Gentile,Campobello di Mazara,NaN,NaN,NaN,Tre Fontane,NaN,NaN,Campobello di Mazara
3,230912,https://www.airbnb.com/rooms/230912,38.17447,12.75140,Sicilia,it,Trapani,91010.0,Via del Secco,NaN,San Vito Lo Capo,NaN,NaN,NaN,NaN,NaN,San Vito Lo Capo
4,137342,https://www.airbnb.com/rooms/137342,36.92940,14.62523,Sicilia,it,Ragusa,97013.0,Strada provinciale Castiglione-Tresauro,NaN,NaN,Ragusa,NaN,NaN,NaN,NaN,Ragusa

In [33]:
re_file_path = data_path + 'derived/re_municipalities.csv'
re_df = pd.read_csv(re_file_path)
re_df.head()

,Unnamed: 0,region,province,city,sale_low,sale_mean,sale_high,rent_low,rent_mean,rent_high,url
0,0,Sicilia,Agrigento,Agrigento,806,945,1262,4.29,5.58,7.11,https://www.immobiliare.it/en/mercato-immobili...
1,1,Sicilia,Agrigento,Alessandria della Rocca,288,376,2407,2.58,4.02,35.53,https://www.immobiliare.it/en/mercato-immobili...
2,2,Sicilia,Agrigento,Aragona,288,634,2407,2.58,2.58,35.53,https://www.immobiliare.it/en/mercato-immobili...
3,3,Sicilia,Agrigento,Bivona,288,300,2407,2.58,4.40,35.53,https://www.immobiliare.it/en/mercato-immobili...
4,4,Sicilia,Agrigento,Burgio,288,288,2407,2.58,4.62,35.53,https://www.immobiliare.it/en/mercato-immobili...

In [34]:
abnb_df[['sale_low', 'sale_mean', 'sale_high']] = np.nan

for index, row in abnb_df.iterrows():
  # print(f"geo_common_name: {row['geo_common_name']}")
  re_match = re_df[re_df['city'] == row['geo_common_name']]
  # print(f"geo_common_name: {row['geo_common_name']}::{len(re_match)}")

  if len(re_match) == 1:
    # print(f"1 MATCH: geo_common_name: {row['geo_common_name']}::{len(re_match)}")  
    
    abnb_df['sale_low'][index] = re_match['sale_low']
    abnb_df['sale_mean'][index] = re_match['sale_mean']
    abnb_df['sale_high'][index] = re_match['sale_high']

  elif len(re_match) > 1:
    print(f"> 1 MATCH: geo_common_name: {row['geo_common_name']}::{len(re_match)}")
  else:
    print(f"NO MATCH: geo_common_name: {row['geo_common_name']}::{len(re_match)}")

abnb_df.head()

NO MATCH: geo_common_name: Lingua::0
NO MATCH: geo_common_name: Carrubbo::0
NO MATCH: geo_common_name: Poggiofelice::0
NO MATCH: geo_common_name: Bafia::0
NO MATCH: geo_common_name: Chianchitta::0

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # This is added back by InteractiveShellApp.init_path()
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if sys.path[0] == '':
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]

NO MATCH: geo_common_name: Raháli::0
NO MATCH: geo_common_name: Chianchitta::0
NO MATCH: geo_common_name: Khamma::0
NO MATCH: geo_common_name: San Giorgio::0
NO MATCH: geo_common_name: Zappardino::0
NO MATCH: geo_common_name: Pianoneve::0
NO MATCH: geo_common_name: Raháli::0
NO MATCH: geo_common_name: Rilievo::0
NO MATCH: geo_common_name: Lampedusa::0
NO MATCH: geo_common_name: Chianchitta::0
NO MATCH: geo_common_name: Chianchitta::0
NO MATCH: geo_common_name: Maugeri::0
NO MATCH: geo_common_name: Calvaruso::0
NO MATCH: geo_common_name: Baglio Belle Scurati::0
NO MATCH: geo_common_name: nan::0
NO MATCH: geo_common_name: Lido Rossello::0
NO MATCH: geo_common_name: Baglio Belle Scurati::0
NO MATCH: geo_common_name: Zappardino::0
NO MATCH: geo_common_name: Castelluzzo::0
NO MATCH: geo_common_name: Calatafimi Segesta::0
NO MATCH: geo_common_name: nan::0
NO MATCH: geo_common_name: Sambuco::0
NO MATCH: geo_common_name: Raháli::0
NO MATCH: geo_common_name: Scauri::0
NO MATCH: geo_common_name: Punta Grande::0
NO MATCH: geo_common_name: Madonnuzza::0
NO MATCH: geo_common_name: Petrulli::0
NO MATCH: geo_common_name: Piano dell'Acqua::0
NO MATCH: geo_common_name: Castelluzzo::0
NO MATCH: geo_common_name: Chianchitta::0
NO MATCH: geo_common_name: San Giorgio::0
NO MATCH: geo_common_name: Lampedusa::0
NO MATCH: geo_common_name: Chianchitta::0
NO MATCH: geo_common_name: Piano Madonna::0

,id,listing_url,latitude,longitude,geo_state,geo_country_code,geo_county,geo_postcode,geo_road,geo_town,geo_village,geo_city,geo_suburb,geo_hamlet,geo_neighbourhood,geo_quarter,geo_common_name,sale_low,sale_mean,sale_high
0,207654,https://www.airbnb.com/rooms/207654,37.61484,15.01867,Sicilia,it,Catania,95030.0,Viale Aldo Moro,NaN,Nicolosi,NaN,NaN,NaN,NaN,NaN,Nicolosi,305.0,1232.0,1797.0
1,125569,https://www.airbnb.com/rooms/125569,37.61566,15.01782,Sicilia,it,Catania,95030.0,Viale Aldo Moro,NaN,Nicolosi,NaN,NaN,NaN,NaN,NaN,Nicolosi,305.0,1232.0,1797.0
2,702537,https://www.airbnb.com/rooms/702537,37.57494,12.74790,Sicilia,it,Trapani,91021.0,Viale Nicolò Gentile,Campobello di Mazara,NaN,NaN,NaN,Tre Fontane,NaN,NaN,Campobello di Mazara,251.0,1116.0,3204.0
3,230912,https://www.airbnb.com/rooms/230912,38.17447,12.75140,Sicilia,it,Trapani,91010.0,Via del Secco,NaN,San Vito Lo Capo,NaN,NaN,NaN,NaN,NaN,San Vito Lo Capo,251.0,2503.0,3204.0
4,137342,https://www.airbnb.com/rooms/137342,36.92940,14.62523,Sicilia,it,Ragusa,97013.0,Strada provinciale Castiglione-Tresauro,NaN,NaN,Ragusa,NaN,NaN,NaN,NaN,Ragusa,638.0,924.0,1894.0

In [35]:
abnb_df[abnb_df['geo_common_name']=='Chianchitta']

,id,listing_url,latitude,longitude,geo_state,geo_country_code,geo_county,geo_postcode,geo_road,geo_town,geo_village,geo_city,geo_suburb,geo_hamlet,geo_neighbourhood,geo_quarter,geo_common_name,sale_low,sale_mean,sale_high
20,533302,https://www.airbnb.com/rooms/533302,37.83188,15.26871,Sicilia,it,Messina,98035.0,NaN,NaN,Chianchitta,NaN,NaN,NaN,Schisò,NaN,Chianchitta,NaN,NaN,NaN
103,2872641,https://www.airbnb.com/rooms/2872641,37.81627,15.26604,Sicilia,it,Messina,98035.0,Viale Jannuzzo,NaN,Chianchitta,NaN,NaN,NaN,Recanati,NaN,Chianchitta,NaN,NaN,NaN
171,8860872,https://www.airbnb.com/rooms/8860872,37.82596,15.26891,Sicilia,it,Messina,98035.0,Via Zara,NaN,Chianchitta,NaN,NaN,NaN,Schisò,NaN,Chianchitta,NaN,NaN,NaN
174,5293956,https://www.airbnb.com/rooms/5293956,37.82363,15.26977,Sicilia,it,Messina,98035.0,Via Larunchi,NaN,Chianchitta,NaN,NaN,NaN,Schisò,NaN,Chianchitta,NaN,NaN,NaN
429,18104738,https://www.airbnb.com/rooms/18104738,37.81836,15.26548,Sicilia,it,Messina,98035.0,Viale Dionisio,NaN,Chianchitta,NaN,NaN,NaN,Recanati,NaN,Chianchitta,NaN,NaN,NaN
464,14742184,https://www.airbnb.com/rooms/14742184,37.81692,15.26367,Sicilia,it,Messina,98035.0,NaN,NaN,Chianchitta,NaN,NaN,NaN,Recanati,NaN,Chianchitta,NaN,NaN,NaN

In [36]:
abnb_df.shape

(500, 20)

In [37]:
abnb_df.dropna(subset=['geo_common_name', 'sale_low', 'sale_mean', 'sale_high'], inplace=True)
abnb_df.shape

(461, 20)

In [38]:
#save the DF so we don't have to keep doing geo lookups
file_path = data_path + f'derived/abnb_geo_with_re_prices_df_{len(abnb_df)}.csv'
abnb_df.to_csv(file_path)